# Generated by Django 5.2.17 on 2026-10-02 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('author', models.CharField(max_length=160, verbose_name='autor')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='categoria')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='exemplares totais')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='exemplares disponíveis')),
                ('shelf_location', models.CharField(blank=True, max_length=120, verbose_name='localização na estante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'livro',
                'verbose_name_plural': 'livros',
                'ordering': ['title', 'author'],
                'constraints': [models.CheckConstraint(condition=models.Q(('available_copies__lte', models.F('total_copies'))), name='available_copies_not_over_total')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='emprestado em')),
                ('due_date', models.DateField(verbose_name='devolução prevista')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='devolvido em')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='catalogo.book', verbose_name='livro')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_loans', to=settings.AUTH_USER_MODEL, verbose_name='leitor')),
            ],
            options={
                'verbose_name': 'empréstimo',
                'verbose_name_plural': 'empréstimos',
                'ordering': ['returned_at', 'due_date', 'book__title'],
            },
        ),
    ]
