# Generated by Django 5.2.17 on 2026-10-02 15:22

import catalogo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Opcional. Envie uma imagem JPG, PNG ou WebP de até 5 MB.', upload_to='capas/', validators=[catalogo.validators.validate_cover_size], verbose_name='imagem da capa'),
        ),
    ]
