# Generated by Django 5.2.17 on 2026-10-02 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_book_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='avaliação')),
                ('comment', models.TextField(max_length=2000, verbose_name='comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalogo.book', verbose_name='livro')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to=settings.AUTH_USER_MODEL, verbose_name='leitor')),
            ],
            options={
                'verbose_name': 'avaliação de livro',
                'verbose_name_plural': 'avaliações de livros',
                'ordering': ['-updated_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('book', 'reader'), name='one_review_per_reader_per_book'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='book_review_rating_between_1_and_5')],
            },
        ),
    ]
